#
# path configuration
#

BOOTS_DIR=$(TOPDIR)/boot
KERNELS_DIR=$(TOPDIR)/kernel
APPS_DIR=$(TOPDIR)/apps
ROOTFS_DIR=$(TOPDIR)/rootfs

BOOT_DIR=$(BOOTS_DIR)/u-boot-2010.06
KERNEL_DIR=$(KERNELS_DIR)/linux-2.6.30.4
OUTPUT_DIR=$(TOPDIR)/output
BUSYB0X_DIR=$(APPS_DIR)/busybox-1.22.1

#install dir

export BOOTS_DIR KERNELS_DIR APPS_DIR ROOTFS_DIR BOOT_DIR KERNEL_DIR BUSYB0X_DIR OUTPUT_DIR
