#ifndef BOARD
#$(error "pls try export BOARD=xxx or make BOARD=xxx")
#endif

CROSS_COMPILE=$(TOOLSCHAIN_DIR)/arm-linux-
#CROSS_COMPILE=arm-linux-gnueabihf-
CC=$(CROSS_COMPILE)gcc
AR=$(CROSS_COMPILE)ar
RANLIB=$(CROSS_COMPILE)ranlib
SSTRIP=$(CROSS_COMPILE)sstrip
LD=$(CROSS_COMPILE)ld
NM=$(CROSS_COMPILE)nm
GCC=$(CROSS_COMPILE)gcc
CXX=$(CROSS_COMPILE)g++
RANLIB=$(CROSS_COMPILE)ranlib
STRIP=$(CROSS_COMPILE)strip
OBJCOPY=$(CROSS_COMPILE)objcopy
OBJDUMP=$(CROSS_COMPILE)objdump
SIZE=$(CROSS_COMPILE)size

export CROSS_COMPILE CC AR RANLIB SSTRIP LD NM GCC CXX RANLIB STRIP OBJCOPY OBJDUMP SIZE BOARD
